services:
    admin.alcogol:
        class: AdminBundle\Admin\AlcogolAdmin
        arguments: [~, AdminBundle\Entity\Alcogol, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Алкоголь }