sonata_admin:
    title:      "Glass"
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list, settings: { groups: [services.group.context]} }
        groups:
            services.group.context:
                label:                Сервисы
                label_catalogue:      AdminBundle
                items:
                    - admin.alcogol
                    - admin.alcogol_categories
                    - admin.articles
                    - admin.banks
                    - admin.broken_glass
                    - admin.company
                    - admin.order_glass
                    - admin.order_glass_status
                    - admin.settings
                    - admin.user