parameters:

    #handlers
    articles_handler.class: SiteBundle\Handler\ArticlesHandler
    articles_handler.entity.class: AdminBundle\Entity\Articles

services:

    #handlers
    articles_handler:
        class: %articles_handler.class%
        arguments:
            - %articles_handler.entity.class%
            - "@doctrine.orm.entity_manager"
            - "@kernel"